version: "3"

services:
  redis:
    container_name: redis_customer
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    build: .
    container_name: app_customer
    command: yarn start:dev
    ports:
      - 3333:3333
    environment:
      - NODE_ENV=stg
      - PORT=3333
      - REDIS_URL=redis://redis:6379
      - KEYCLOAK_TOKEN=https://accounts.seguros.vitta.com.br/auth/realms/careers/protocol/openid-connect/token
      - KEYCLOAK_USERINFO=https://accounts.seguros.vitta.com.br/auth/realms/careers/protocol/openid-connect/userinfo
    volumes:
      - /www/stone-customer-api
    links:
      - redis
    depends_on:
      - redis
